server:
  port: 8000
#  context-path: /api

logging:
  config: logback.xml

spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/xmo_demo?useUnicode:true&amp;characterEncoding:utf8
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 20971520
  ######## mail configuration
  mail:
    host: smtp.mxhichina.com
    username: test@xmomen.com
    password: aaaaa888*
    properties:
      mail:
        smtp:
          auth: true
          port: 25
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
#druid datasource
druid:
  initialSize: 10
  minIdle: 10
  maxActive: 50
  maxWait: 60000
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: 300000
  validationQuery: SELECT 'x' FROM DUAL
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false
  poolPreparedStatements: true
  maxPoolPreparedStatementPerConnectionSize: 20
  filters: wall,stat

# oss
oss:
  accessKeyId: LTAIQ9tAnQKgixOa
  accessKeySecret: SvUzBFGETJ3k9DUY0krXEKLYEpOsFF
  bucketName: xmomen-test
  endpoint: oss-cn-hangzhou.aliyuncs.com

# mybatis
mybatis:
  typeAliasesPackage: com.**.entity
  mapperLocations: classpath*:com/**/mapper/*.xml
  configLocation: classpath:config/mybatis-config.xml

# security
jwt:
  secret: xmomen
  expiration: 1800
security:
  remember-me.key: xmomen_remember_me

jog:
  cron:
    simpleJob: 0/5 * * * * ?
